### ISSUE TITLE
TypeError: Expected bytes, got str.

### ISSUE THREAD

**Issue by zhaopengpeng8866** [XiaohangZhan/deocclusion#2]
Hello, I encountered such an error:
Traceback (most recent call last):
File "./coco.py", line 498, in
layers='heads')
File "/data/g/weidaihua/Mask_RCNN-master/model.py", line 2207, in train
validation_data=next(val_generator),
File "/data/g/weidaihua/Mask_RCNN-master/model.py", line 1604, in data_generator
use_mini_mask=config.USE_MINI_MASK)
File "/data/g/weidaihua/Mask_RCNN-master/model.py", line 1163, in load_image_gt
mask, class_ids = dataset.load_mask(image_id)
File "./coco.py", line 249, in load_mask
image_info["width"])
File "./coco.py", line 308, in annToMask
rle = self.annToRLE(ann, height, width)
File "./coco.py", line 294, in annToRLE
rle = maskUtils.merge(rles)
File "pycocotools/_mask.pyx", line 145, in pycocotools._mask.merge (pycocotools/_mask.c:3173)
File "pycocotools/_mask.pyx", line 122, in pycocotools._mask._frString (pycocotools/_mask.c:2605)
TypeError: Expected bytes, got str.
How to solve this? Thanks!

**Comment by XiaohangZhan** [comment]
There is no coco.py in my repo. Are you sure it is an issue of this repo "deocclusion"?

**Comment by zhaopengpeng8866** [comment]
Sorry, the above is the code I found when I searched Google for the same error. I accidentally copied it. The following is the error I reported while training under the deocclusion file:
  Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main(args)
  File "main.py", line 31, in main
    trainer.run()
  File "/home/peng/python_pro/pig_pro/deocclusion-master/trainer.py", line 122, in run
    self.validate('on_val')
  File "/home/peng/python_pro/pig_pro/deocclusion-master/trainer.py", line 206, in validate
    for i, inputs in enumerate(self.val_loader):
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/partial_comp_dataset.py", line 116, in __getitem__
    idx, load_rgb=self.config['load_rgb'], randshift=True) # modal, uint8 {0, 1}
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/partial_comp_dataset.py", line 69, in _get_inst
    modal, bbox, category, imgfn, _ = self.data_reader.get_instance(idx)
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/reader.py", line 108, in get_instance
    modal, bbox, category = read_COCOA(reg, h, w)
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/reader.py", line 52, in read_COCOA
    modal = maskUtils.decode(rle).squeeze()
  File "pycocotools/_mask.pyx", line 138, in pycocotools._mask.decode
  File "pycocotools/_mask.pyx", line 122, in pycocotools._mask._frString
TypeError: Expected bytes, got str.
How should it be solved? Thank you!

**Comment by zhaopengpeng8866** [comment]
> 
> 
> There is no coco.py in my repo. Are you sure it is an issue of this repo "deocclusion"?

Sorry, the above is the code I found when I searched Google for the same error. I accidentally copied it. The following is the error I reported while training under the deocclusion file:
  Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main(args)
  File "main.py", line 31, in main
    trainer.run()
  File "/home/peng/python_pro/pig_pro/deocclusion-master/trainer.py", line 122, in run
    self.validate('on_val')
  File "/home/peng/python_pro/pig_pro/deocclusion-master/trainer.py", line 206, in validate
    for i, inputs in enumerate(self.val_loader):
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/partial_comp_dataset.py", line 116, in __getitem__
    idx, load_rgb=self.config['load_rgb'], randshift=True) # modal, uint8 {0, 1}
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/partial_comp_dataset.py", line 69, in _get_inst
    modal, bbox, category, imgfn, _ = self.data_reader.get_instance(idx)
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/reader.py", line 108, in get_instance
    modal, bbox, category = read_COCOA(reg, h, w)
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/reader.py", line 52, in read_COCOA
    modal = maskUtils.decode(rle).squeeze()
  File "pycocotools/_mask.pyx", line 138, in pycocotools._mask.decode
  File "pycocotools/_mask.pyx", line 122, in pycocotools._mask._frString
TypeError: Expected bytes, got str.
How should it be solved? Thank you!

**Comment by zhaopengpeng8866** [comment]
> 
> 
> There is no coco.py in my repo. Are you sure it is an issue of this repo "deocclusion"?
