### ISSUE TITLE
please help：subprocess.CalledProcessError: Command '['/home/wwx/anaconda3/envs/deo/bin/python', '-u', 'main.py', '--local_rank=0', '--config', 'experiments/KINS/pcnet_m/config.yaml', '--launcher', 'pytorch']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by zhenghan408** [XiaohangZhan/deocclusion#23]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from trainer import Trainer
  File "/media/wwx/B8D46DEEC022AA4B/deocclusion-master/trainer.py", line 14, in <module>
    import datasets
  File "/media/wwx/B8D46DEEC022AA4B/deocclusion-master/datasets/__init__.py", line 1, in <module>
    from .reader import *
  File "/media/wwx/B8D46DEEC022AA4B/deocclusion-master/datasets/reader.py", line 8, in <module>
    import pycocotools.mask as maskUtils
ModuleNotFoundError: No module named 'pycocotools'
Traceback (most recent call last):
  File "/home/wwx/anaconda3/envs/deo/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wwx/anaconda3/envs/deo/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wwx/anaconda3/envs/deo/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/wwx/anaconda3/envs/deo/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/wwx/anaconda3/envs/deo/bin/python', '-u', 'main.py', '--local_rank=0', '--config', 'experiments/KINS/pcnet_m/config.yaml', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by zhenghan408** [comment]
用的KINS数据集和train PCNet-M

**Comment by XiaohangZhan** [comment]
Did you install pycocotools following the readme?

**Comment by zhenghan408** [comment]
yes,i'm sure

**Comment by zhenghan408** [comment]
bro~Any other Suggestions?

**Comment by XiaohangZhan** [comment]
It looks like pycocotools is not correctly installed.
