### ISSUE TITLE
TypeError: Expected bytes, got str.

### ISSUE THREAD

**Issue by zhaopengpeng8866** [XiaohangZhan/deocclusion#3]
Sorry, the above is the code I found when I searched Google for the same error. I accidentally copied it. The following is the error I reported while training under the deocclusion file:
  Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main(args)
  File "main.py", line 31, in main
    trainer.run()
  File "/home/peng/python_pro/pig_pro/deocclusion-master/trainer.py", line 122, in run
    self.validate('on_val')
  File "/home/peng/python_pro/pig_pro/deocclusion-master/trainer.py", line 206, in validate
    for i, inputs in enumerate(self.val_loader):
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/peng/anaconda3/envs/tpy36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/partial_comp_dataset.py", line 116, in __getitem__
    idx, load_rgb=self.config['load_rgb'], randshift=True) # modal, uint8 {0, 1}
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/partial_comp_dataset.py", line 69, in _get_inst
    modal, bbox, category, imgfn, _ = self.data_reader.get_instance(idx)
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/reader.py", line 108, in get_instance
    modal, bbox, category = read_COCOA(reg, h, w)
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/reader.py", line 52, in read_COCOA
    modal = maskUtils.decode(rle).squeeze()
  File "pycocotools/_mask.pyx", line 138, in pycocotools._mask.decode
  File "pycocotools/_mask.pyx", line 122, in pycocotools._mask._frString
TypeError: Expected bytes, got str.
How should it be solved? Thank you!

**Comment by XiaohangZhan** [comment]
What's the version of pycocotools? I'm using pip install pycocotools==2.0

**Comment by zhaopengpeng8866** [comment]
> 
> 
> What's the version of pycocotools? I'm using pip install pycocotools==2.0

Yes, the version of pycocotools I use is also 2.0，but it still reports the above error.

**Comment by XiaohangZhan** [comment]
Please uninstall your current pycocotools and try to install it following the instructions in https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md

**Comment by zhaopengpeng8866** [comment]
> 
> 
> Please uninstall your current pycocotools and try to install it following the instructions in https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md

That's right, the above error has been resolved, thank you. But during training, I encountered the following problem again.
    RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 10.76 GiB total capacity; 3.15 GiB already allocated; 18.56 MiB free; 47.15 MiB cached);

 Is it because of batch size? Is it something else?

**Comment by XiaohangZhan** [comment]
Please check if all GPUs involved are empty? I guess certain processes already occupied some memories on GPU 0. The GPU usage for PCNet-M is around 6.55G, and that for PCNet-C is around 7.85G, 10.96G should be enough.

**Comment by zhaopengpeng8866** [comment]
> 
> 
> Please check if all GPUs involved are empty? I guess certain processes already occupied some memories on GPU 0. The GPU usage for PCNet-M is around 6.55G, and that for PCNet-C is around 7.85G, 10.96G should be enough.

Yes, I think so too. Before I started training, I had checked the usage of 4 GPU cards, and the threads of each GPU were killed; by watch -n -0.1 nvidia-smi instruction, in Processes The following also shows the video memory used by each process on each GPU: No running processing found. But when I start training, ie input the command sh experiments/COCOA/pcnet_m/train.sh, each gpu card still reports the following error:
  [2020-04-28 09: 20: 13,231] Validation Iter: [0] Time 0.368 (1.301) Data 0.022 (0.442) loss: 1.183 (1.18)
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main (args)
  File "main.py", line 31, in main
    trainer.run ()
  File "/home/peng/python_pro/pig_pro/deocclusion-master/trainer.py", line 125, in run
    self.train ()
  File "/home/peng/python_pro/pig_pro/deocclusion-master/trainer.py", line 147, in train
    loss_dict = self.model.step ()
  File "/home/peng/python_pro/pig_pro/deocclusion-master/models/partial_completion_mask.py", line 121, in step
    output = self.model (torch.cat ([self.mask, self.eraser], dim = 1))
  File "/home/peng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward (* input, ** kwargs)
  File "/home/peng/python_pro/pig_pro/deocclusion-master/utils/distributed_utils.py", line 18, in forward
    return self.module (* inputs, ** kwargs)
  File "/home/peng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward (* input, ** kwargs)
  File "/home/peng/python_pro/pig_pro/deocclusion-master/models/backbone/unet/unet_model.py", line 74, in forward
    x = self.up4 (x, x1)
  File "/home/peng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward (* input, ** kwargs)
  File "/home/peng/python_pro/pig_pro/deocclusion-master/models/backbone/unet/unet_parts.py", line 76, in forward
    x = torch.cat ([x2, x1], dim = 1)
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 3; 10.76 GiB total capacity; 3.47 GiB already allocated; 438.56 MiB free; 77.15 MiB cached);
  
    So I don’t know what caused it? Ask for advice, thanks!

**Comment by XiaohangZhan** [comment]
I noticed that you have 4 GPUs. Please set `--nproc_per_node=4` in `train.sh`.
If it does not work, below are some suggestions for debugging: switch off the validation flag in the config `initial_val = False`, use a very small batch size `batch_size=2`, and see if it still runs out of the memory.

**Comment by zhaopengpeng8866** [comment]
> 
> 
> I noticed that you have 4 GPUs. Please set `--nproc_per_node=4` in `train.sh`.
> If it does not work, below are some suggestions for debugging: switch off the validation flag in the config `initial_val = False`, use a very small batch size `batch_size=2`, and see if it still runs out of the memory.

 The setting  ‘--nproc_per_node = 4’ in `train.sh` is correct. Now, there is no problem with training, thank you!

**Comment by XiaohangZhan** [comment]
Cheers!
