### ISSUE TITLE
ValueError: Unexpected option: --local_rank=0

### ISSUE THREAD

**Issue by XDhughie** [XiaohangZhan/deocclusion#4]
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1961, in main
    setup = process_command_line(sys.argv)
  File "/root/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_command_line_handling.py", line 145, in process_command_line
    raise ValueError("Unexpected option: " + argv[i])
ValueError: Unexpected option: --local_rank=0
Usage:
pydevd.py --port N [(--client hostname) | --server] --file executable [file_options]

Process finished with exit code 0

when i debug，the error occurs。

**Comment by XiaohangZhan** [comment]
Pycharm may not support distributed training. Please launch it via the command line according to README.
