### ISSUE TITLE
NameError: name 'mc' is not defined

### ISSUE THREAD

**Issue by zhaopengpeng8866** [XiaohangZhan/deocclusion#7]
When I run sh experiments/COCOA/pcnet_c/train.sh, the following error is reported：
Original Traceback (most recent call last):
  File "/home/peng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/peng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/peng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/partial_comp_content_dataset.py", line 114, in __getitem__
    self._init_memcached()
  File "/home/peng/python_pro/pig_pro/deocclusion-master/datasets/partial_comp_content_dataset.py", line 51, in _init_memcached
    self.mclient = mc.MemcachedClient.GetInstance(server_list_config_file, client_config_file)
NameError: name 'mc' is not defined.    
How to deal with it? Thanks!

**Comment by XiaohangZhan** [comment]
Did you change `memcached` to True in `experiments/COCOA/pcnet_c/config.yaml`? It should be False by default.

**Comment by zhaopengpeng8866** [comment]
> 
> 
> Did you change `memcached` to True in `experiments/COCOA/pcnet_c/config.yaml`? It should be False by default.

Yes, I have changed `memcached` to True in `experiments/COCOA/pcnet_c/config.yaml`，but still reported the same error.

**Comment by XiaohangZhan** [comment]
I mean, you should not change it to True, cause you do not have the memcache client. Set it to False and there should not be the error. Have you pulled the latest version?

**Comment by zhaopengpeng8866** [comment]
> 
> 
> I mean, you should not change it to True, cause you do not have the memcache client. Set it to False and there should not be the error. Have you pulled the latest version?

It ’s the previous version, now I ’ll download the latest version as you said, and try again. Thank you!
